(()=>{
  'use strict';
  const STORAGE='nineyin-language';
  const RU='ru',EN='en';
  const dict={
    'Главная':'Home','Форум':'Forum','Пользователи':'Users','Создать запись':'Create post','Мой профиль':'My profile','Руководство':'Guide','О персонаже':'Character','Партнёрство и связь':'Partnership & contact','Регистрация':'Registration','Пополнение':'Top up','Войти':'Sign in','Выйти':'Sign out','Очистить':'Clear',
    'Доступ к сайту':'Site access','Доступ к форуму':'Forum access','Войдите в общий аккаунт Руководства и Форума.':'Sign in to your shared Guide and Forum account.','СООБЩЕСТВО 9 ИНЬ':'9 YIN COMMUNITY','Войти в аккаунт':'Sign in','РЕГИСТРАЦИЯ':'REGISTER','Войти':'Sign in','Создать аккаунт':'Create account','Email':'Email','Пароль':'Password','Повторите пароль':'Repeat password',
    'После регистрации нужно заполнить профиль. На Форуме в разделе «Пользователи» будут видны только фото профиля и игровой ник. Остальная информация хранится в разделе «Мой профиль». Email остаётся скрытым.':'After registration, complete your profile. The Forum Users section shows only your profile picture, game nickname and server. Other information stays in My Profile. Your email remains private.',
    'Создайте профиль':'Create your profile','Заполните обязательные данные. Фото можно оставить стандартным.':'Fill in the required fields. You can keep the default profile picture.','Фото профиля':'Profile picture','Можно пропустить — тогда останется стандартное изображение «Нет фото профиля».':'Optional — the default “No profile photo” image will remain.','Имя на сайте':'Display name','Например: Soyeon':'For example: Soyeon','Игровой никнейм':'Game nickname','Ваш ник в игре':'Your in-game nickname','Игровой ник':'Game nickname','Сервер':'Server','Выберите сервер':'Select server','О себе':'About me','Расскажите немного о себе и своём опыте в игре':'Tell the community a little about yourself and your experience in the game','Сохранить профиль и открыть сайт':'Save profile and enter site',
    'Тайвань':'Taiwan','Пиратка CN':'Pirate CN','Америка':'America','Китай':'China','Малайзия':'Malaysia','Тайвань и Пиратка CN':'Taiwan + Pirate CN','Сервер не выбран':'Server not selected',
    'Аккаунт создан. Подтвердите email по письму, затем войдите.':'Account created. Confirm your email using the link in the message, then sign in.','Выполняется вход...':'Signing in...','Создаём аккаунт...':'Creating account...','Неверный email или пароль.':'Incorrect email or password.','Пароли не совпадают.':'Passwords do not match.','Минимум 8 символов.':'Minimum 8 characters.','Такой email уже зарегистрирован.':'This email is already registered.','Не удалось зарегистрироваться.':'Registration failed.','Не удалось войти.':'Sign-in failed.','Заполните все обязательные поля.':'Fill in all required fields.','Профиль сохранён.':'Profile saved.','Не удалось сохранить профиль.':'Could not save profile.','Сохраняем...':'Saving...','Изменения сохранены.':'Changes saved.','Выберите область изображения':'Choose the visible area','Перемещайте фотографию внутри круглой рамки и настройте масштаб.':'Drag the photo inside the circular frame and adjust the zoom.','Предпросмотр':'Preview','Масштаб':'Zoom','В профиле будет отображаться только область внутри круглой рамки.':'Only the area inside the circular frame will be shown in your profile.','Применить':'Apply','Область фото выбрана. Нажмите «Сохранить изменения».':'Photo area selected. Click “Save changes”.','Не удалось открыть изображение.':'Could not open the image.','Не удалось обработать изображение':'Could not process the image',
    'Аккаунт заблокирован':'Account blocked','Доступ ограничен':'Access restricted','Аккаунт заблокирован при подозрении на бот-активность. Для восстановления доступа свяжитесь с администратором.':'This account has been blocked due to suspected bot activity. Contact the administrator to restore access.','Связаться с администратором':'Contact administrator','Выйти из аккаунта':'Sign out',
    'СООБЩЕСТВО':'COMMUNITY','Подтверждённые участники сообщества. Показываются фото профиля, игровой никнейм и выбранный сервер. Неподтверждённые и заблокированные аккаунты видны только администратору.':'Verified community members. Profile photo, game nickname and selected server are shown. Unverified and blocked accounts are visible only to the administrator.','Найти по игровому нику...':'Search by game nickname...','пользователей':'users','Пользователи не найдены.':'No users found.','Ошибка загрузки пользователей:':'Could not load users:','Активен':'Active','Заблокирован':'Blocked','Не подтвержден':'Unverified','Не подтвержден · Заблокирован':'Unverified · Blocked','Заблокировать':'Block','Разблокировать':'Unblock','Администратор':'Administrator','Профиль не заполнен':'Profile incomplete','Без игрового ника':'No game nickname','Не удалось изменить статус пользователя.':'Could not change user status.','Заблокировать пользователя':'Block user','Разблокировать пользователя':'Unblock user','пользователя':'user',
    'ЛИЧНЫЙ РАЗДЕЛ':'PERSONAL AREA','Личные данные профиля и информация «О себе». Email виден только вам и не публикуется в каталоге пользователей.':'Your profile details and About Me information. Your email is visible only to you and is never published in the user directory.','Профиль':'Profile','На сайте с':'Member since','Редактировать профиль':'Edit profile','Новое фото профиля':'New profile picture','Сохранить изменения':'Save changes',
    'Все записи':'All posts','Поиск по форуму...':'Search the forum...','Назад':'Back','Вперёд':'Next','Открыть':'Open','Закрепить':'Pin','Открепить':'Unpin','Комментарии':'Comments','Ваш комментарий':'Your comment','Напишите комментарий или выберите стикер...':'Write a comment or choose a sticker...','Стикеры':'Stickers','Прикрепить файлы':'Attach files','Отправить':'Send','Мужские':'Male','Женские':'Female','Выбран стикер':'Selected sticker','Убрать':'Remove','Загрузка комментариев...':'Loading comments...','Изображения к записи':'Post images','Закреплено':'Pinned',
    'Школы, Фракции, Секты':'Schools, Factions & Sects','Пути развития':'Paths of Progression','Школы':'Schools','Фракции':'Factions','Секты':'Sects','Направление обучения':'Training path','Союзы мира':'World alliances','Особые пути':'Special paths','Основные направления обучения, требования для вступления и доступные боевые стили.':'Core schools, entry requirements and available combat styles.','Особенности репутации, задания и награды за развитие отношений.':'Reputation features, quests and rewards for building relations.','Условия принятия, уникальные навыки и ограничения особых путей развития.':'Entry conditions, unique skills and restrictions of special paths.',
    'Эмей':'Emei','Лейб-Гвардия':'Royal Guard','Города Наказаний':'Punishment City','Город Наказаний':'Punishment City','Блаженных':'Blissful Valley','Блаженные':'Blissful Valley','Тан':'Tang Clan','Шаолинь':'Shaolin','Ученые':'Scholars','Минг':'Ming Sect','Куньлунь':'Kunlun','Удан':'Wudang','Нищих':'Beggars’ Sect','Нищие':'Beggars’ Sect','Тяньшань':'Tianshan','Святилище Шаманов':'Shaman Sanctuary','Лазурная Стража':'Azure Guard','Клан Безродных':'Rootless Clan','Усадьба Зверей':'Beast Villa','Дворец Цветов':'Flower Palace','Усадьба Сюй':'Xu Manor','Остров Персиков':'Peach Blossom Island','Семья Шень':'Shen Family','Храм Небесного Колеса':'Heavenly Wheel Temple','Остров Сияющих Надежд':'Island of Shining Hope',
    'Руководство Легенды Кунг-Фу 2026':'Kung Fu Legends Guide 2026','ФОРУМ ЛЕГЕНДЫ КУНГ-ФУ 2026':'KUNG FU LEGENDS FORUM 2026','Подробнее':'Learn more','Сказать Спасибо':'Say Thank You','Поддержать автора':'Support the author','Нажмите, чтобы открыть':'Click to open','Отсканируйте QR-код или нажмите на него':'Scan the QR code or click it',
    'Без названия':'Unnamed','Жду ответа':'Awaiting reply','Завершен':'Completed','Каталог питомцев':'Pet catalog','Коллекция питомцев':'Pet collection','На каждой странице отображается по 10 питомцев.':'Each page shows 10 pets.','Название не добавлено':'Name not added','Нет описания':'No description','Коричневый Орел':'Brown Eagle','Бесконечные голуби':'Infinite pigeons','КОД ПИТОМЦА':'PET CODE','Не указан':'Not specified','Страница 1 из 2':'Page 1 of 2','Страницы каталога питомцев':'Pet catalog pages','Номера страниц':'Page numbers','Гора Хуа':'Mount Hua','Морской Дворец Тианья':'Tianya Sea Palace','Дамба Няньло':'Nianluo Dam','Древняя Гробница':'Ancient Tomb','Пять Бессмертных':'Five Immortals','Дворец Святой Воды':'Holy Water Palace','Лагерь Шеньчжи':'Shenzhi Camp','Павильон Звездного Неба':'Starry Sky Pavilion','Конвой Чан Фэн':'Chang Feng Escort','Секта Дхармы':'Dharma Sect','Мастерская Радости':'Joy Workshop','Кровавая Сабля':'Blood Saber','English':'English','Русский':'Russian'
  };
  const originalText=new WeakMap(), originalAttrs=new WeakMap();
  let lang=(localStorage.getItem(STORAGE)||RU).toLowerCase()==='en'?EN:RU;
  const t=(s)=>{s=String(s??'');if(lang!==EN)return s;if(dict[s])return dict[s];
    let m=s.match(/^Игровой ник:\s*(.+)$/);if(m)return `Game nickname: ${m[1]}`;
    m=s.match(/^Страница (\d+) из (\d+)$/);if(m)return `Page ${m[1]} of ${m[2]}`;
    m=s.match(/^(\d+) пользователей$/);if(m)return `${m[1]} users`;
    return s;};
  function shouldSkip(el){return !el||el.closest?.('script,style,textarea,code,pre,.notranslate,[data-i18n-skip]');}
  function translateTextNode(n){if(!n||!n.parentElement||shouldSkip(n.parentElement))return;if(!originalText.has(n))originalText.set(n,n.nodeValue);const base=originalText.get(n);if(lang===RU){if(n.nodeValue!==base)n.nodeValue=base;return;}const lead=base.match(/^\s*/)[0],trail=base.match(/\s*$/)[0],core=base.trim();if(!core)return;const translated=t(core);if(translated!==core){const desired=lead+translated+trail;if(n.nodeValue!==desired)n.nodeValue=desired;}}
  function translateElement(el){if(!el||shouldSkip(el))return;for(const a of ['placeholder','aria-label','title','alt']){if(!el.hasAttribute?.(a))continue;let map=originalAttrs.get(el);if(!map){map={};originalAttrs.set(el,map)}if(!(a in map))map[a]=el.getAttribute(a);el.setAttribute(a,lang===RU?map[a]:t(map[a]));}}
  function walk(root=document.body){if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode())translateTextNode(n);if(root.nodeType===1)translateElement(root);root.querySelectorAll?.('*').forEach(translateElement);if(document.title){if(!document.documentElement.dataset.originalTitle)document.documentElement.dataset.originalTitle=document.title;document.title=lang===RU?document.documentElement.dataset.originalTitle:t(document.documentElement.dataset.originalTitle)}}
  function injectStyle(){if(document.getElementById('nineyinLangStyle'))return;const st=document.createElement('style');st.id='nineyinLangStyle';st.textContent=`.nineyin-language-switch{appearance:none;border:1px solid rgba(226,183,93,.52);background:rgba(4,18,29,.86);color:#f0d28b;border-radius:2px;padding:7px 10px;min-width:44px;font:700 11px/1 'Golos Text',Arial,sans-serif;letter-spacing:.08em;cursor:pointer;white-space:nowrap}.nineyin-language-switch:hover{border-color:#f1ca70;color:#fff0bf}.topnav .nineyin-language-switch{margin-left:4px}.top-nav .nineyin-language-switch{align-self:center}.goog-te-banner-frame.skiptranslate,.goog-te-banner-frame,iframe.VIpgJd-ZVi9od-ORHb-OEVmcd{display:none!important;visibility:hidden!important;height:0!important}html,body{top:0!important;margin-top:0!important}#nineyinGoogleTranslate{position:fixed;left:-9999px;top:-9999px;width:1px;height:1px;overflow:hidden}.goog-te-gadget{font-size:0!important}`;document.head.appendChild(st)}
  function clearGoogleCookie(){for(const path of ['/']){document.cookie=`googtrans=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=${path}`;document.cookie=`googtrans=/ru/ru;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=${path}`;}}
  function setLanguage(next){next=next==='en'?EN:RU;localStorage.setItem(STORAGE,next);if(next===EN){document.cookie='googtrans=/ru/en;path=/;SameSite=Lax'}else clearGoogleCookie();location.reload();}
  function injectSwitch(){const nav=document.querySelector('.topnav,.top-nav');if(!nav||nav.querySelector('.nineyin-language-switch'))return;const b=document.createElement('button');b.type='button';b.className='nineyin-language-switch notranslate';b.textContent=lang===EN?'RU':'EN';b.title=lang===EN?'Русский':'English';b.setAttribute('aria-label',b.title);b.addEventListener('click',()=>setLanguage(lang===EN?RU:EN));nav.appendChild(b)}
  function loadGoogle(){if(lang!==EN||document.getElementById('googleTranslateScript'))return;let host=document.getElementById('nineyinGoogleTranslate');if(!host){host=document.createElement('div');host.id='nineyinGoogleTranslate';document.body.appendChild(host)}window.googleTranslateElementInit=()=>{try{new google.translate.TranslateElement({pageLanguage:'ru',includedLanguages:'en',autoDisplay:false,multilanguagePage:false},'nineyinGoogleTranslate');const apply=()=>{const c=document.querySelector('.goog-te-combo');if(c&&c.value!=='en'){c.value='en';c.dispatchEvent(new Event('change',{bubbles:true}))}};setTimeout(apply,150);setTimeout(apply,700)}catch(e){console.warn('English translation service unavailable',e)}};const s=document.createElement('script');s.id='googleTranslateScript';s.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';s.async=true;s.onerror=()=>console.warn('English translation service could not be loaded');document.head.appendChild(s)}
  const nativeAlert=window.alert.bind(window),nativeConfirm=window.confirm.bind(window);
  window.alert=(msg)=>nativeAlert(lang===EN?t(String(msg??'')):msg);
  window.confirm=(msg)=>nativeConfirm(lang===EN?t(String(msg??'')):msg);
  function init(){document.documentElement.lang=lang;injectStyle();injectSwitch();walk();if(lang===EN)loadGoogle();const obs=new MutationObserver(ms=>{for(const m of ms){if(m.type==='characterData')translateTextNode(m.target);for(const n of m.addedNodes){if(n.nodeType===3)translateTextNode(n);else if(n.nodeType===1){walk(n);if(n.matches?.('.topnav,.top-nav')||n.querySelector?.('.topnav,.top-nav'))injectSwitch()}}}});obs.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:false});window.dispatchEvent(new CustomEvent('nineyin:language-ready',{detail:{language:lang}}))}
  window.NineYinI18n={t,getLanguage:()=>lang,setLanguage,dictionary:dict};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
